FROM debian:{{env "DEBIAN_RELEASE"}}

ENV GLUSTER_MOUNTPOINT=/gluster_mount/shared0
ENV GLUSTERFS_VERSION_MAJOR={{env "GLUSTERFS_VERSION_MAJOR"}}
ENV GLUSTERFS_VERSION_MINOR={{env "GLUSTERFS_VERSION_MINOR"}}

COPY root /

# wget -O - https://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub | apt-key add - && \

RUN \
    apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y wget ca-certificates && \
    wget -O - http://download.gluster.org/pub/gluster/glusterfs/3.12/rsa.pub | apt-key add - && \
    echo deb https://download.gluster.org/pub/gluster/glusterfs/${GLUSTERFS_VERSION_MAJOR}/${GLUSTERFS_VERSION_MAJOR}.${GLUSTERFS_VERSION_MINOR}/Debian/jessie/apt/ jessie main > /etc/apt/sources.list.d/gluster.list && \
    wget https://github.com/Yelp/dumb-init/releases/download/v1.1.1/dumb-init_1.1.1_amd64.deb && \
    dpkg -i dumb-init_1.1.1_amd64.deb && \
    apt-get remove -y wget ca-certificates && \
    apt-get autoremove -y && \
    chmod +x /usr/local/bin/*
    
VOLUME ["${GLUSTER_MOUNTPOINT}"]
    
CMD ["/usr/local/bin/run-init.sh"]
