kind: List
apiVersion: v1
items:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: glusterfs-d78-327
- kind: Service
  apiVersion: v1
  metadata:
    name: gfs-strg-d78-327
  spec:
    ports:
    - name: ssh
      port: 2222
      targetPort: 2222
    - name: glusterfs-api
      port: 24007
      targetPort: 24007
    - name: glusterfs-infiniband
      port: 24008
      targetPort: 24008
    - name: glusterfs-brick0
      port: 49152
      targetPort: 49152
    - name: glusterfs-nfs-0
      port: 38465
      targetPort: 38465
    - name: glusterfs-nfs-1
      port: 38466
      targetPort: 38466
    - name: glusterfs-nfs-2
      port: 38467
      targetPort: 38467
    - name: nfs-rpc
      port: 111
      targetPort: 111
    - name: nfs-rpc-udp
      port: 111
      targetPort: 111
      protocol: UDP
    - name: nfs-portmap
      port: 2049
      targetPort: 2049
    selector:
      component: gfs-strg-d78-327
- kind: Service
  apiVersion: v1
  metadata:
    name: jenkins
  spec:
    ports:
    - port: 8080
    type: nodePort
    selector:
      component: 
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      component: gfs-strg-d78-327
    name: gfs-strg-d78-327
  spec:
    replicas: 2
    selector:
      component: gfs-strg-d78-327
    template:
      metadata:
        labels:
          component: gfs-strg-d78-327
      spec:
        serviceAccount: glusterfs-d78-327
        containers:
        - name: gfs-srv-d78-327
          image: matthewvalimaki/glusterfs-kubernetes-server-debian7.8-3.2.7:latest
          securityContext:
            privileged: true
          ports:
          - containerPort: 2222
          - containerPort: 24007
          - containerPort: 24008
          - containerPort: 49152
          - containerPort: 38465
          - containerPort: 38466
          - containerPort: 38467
          - containerPort: 2049
          - containerPort: 111
          - containerPort: 111
            protocol: UDP
          env:
          - name: GLUSTER_VOLUME_TYPE
            value: distributed
          - name: GLUSTER_BRICK_PATH
            value:
          - name: GLUSTER_VOL
            value: shared0
          - name: GLUSTER_BRICK_PATH
            value: /gluster_volume
          - name: SERVICE_NAME
            value: gfs-strg-d78-327.default.svc.cluster.local
          - name: ROOT_PASSWORD
            value: container_root_password
          - name: DEBUG
            value: "1"
          - name: SSH_PORT
            value: "2222"
          volumeMounts:
          - mountPath: /gluster_volume
            name: local0
        volumes:
          - name: local0
            hostPath:
              path: /data
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      component: gfs-c-d78-327
    name: gfs-c-d78-327
  spec:
    replicas: 2
    selector:
      component: gfs-c-d78-327
    template:
      metadata:
        labels:
          component: gfs-c-d78-327
      spec:
        containers:
        - name: gfs-c-d78-327
          image: matthewvalimaki/glusterfs-kubernetes-client-debian7.8-3.2.7
          securityContext:
            privileged: true
          env:
          - name: GLUSTER_VOLUME_SERVER
            value: gfs-strg-d78-327.default.svc.cluster.local
          - name: GLUSTER_VOLUMEID
            value: shared01
          - name: GLUSTER_MOUNTPOINT
            value: /gluster_mount/shared01
          volumeMounts:
            - name: shared01
              mountPath: /gluster_mount
        - name: jenkins
          image: jenkins
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            -
              name: JAVA_OPTS
              value: "-javaagent:/opt/newrelic/newrelic-agent.jar -Dnewrelic.config.log_file_path=/opt/newrelic/logs -Dnewrelic.config.license_key=$NEW_RELIC_LICENSE_KEY -Dnewrelic.config.app_name=$NEW_RELIC_APP_NAME -Dnewrelic.config.labels=$NEW_RELIC_LABELS"
        volumes:
          - name: shared01
            emptyDir: {}