apiVersion: v1
kind: Service
metadata:
  name: gfs-strg-d78-327
spec:
  ports:
  - name: ssh
    port: 2222
    targetPort: 2222
  - name: glusterfs-api
    port: 24007
    targetPort: 24007
  - name: glusterfs-infiniband
    port: 24008
    targetPort: 24008
  - name: glusterfs-brick0
    port: 49152
    targetPort: 49152
  - name: glusterfs-nfs-0
    port: 38465
    targetPort: 38465
  - name: glusterfs-nfs-1
    port: 38466
    targetPort: 38466
  - name: glusterfs-nfs-2
    port: 38467
    targetPort: 38467
  - name: nfs-rpc
    port: 111
    targetPort: 111
  - name: nfs-rpc-udp
    port: 111
    targetPort: 111
    protocol: UDP
  - name: nfs-portmap
    port: 2049
    targetPort: 2049
  selector:
    component: gfs-strg-d78-327