#!/bin/bash
export BUILD_SETUP=1
export DOCKER_UID=davidwalter
export DEBIAN_RELEASE=9.2
export DEBIAN_RELEASE_NAME=stretch
export NAMESPACE=default
export GFS_VERSION_MAJOR=3.12
export GFS_VERSION_MINOR=2
export GFS_VERSION=${GFS_VERSION_MAJOR}.${GFS_VERSION_MINOR}
export GFS_VERSION_PATH=${GFS_VERSION_MAJOR}/${GFS_VERSION}
export SSH_PORT=2222
export GLUSTER_VOL=vol0
export GLUSTER_BRICK_PATH=/gfs
# if you need more version specific services
# export GFS_SERVER_NAME=gfs-${GFS_VERSION_MAJOR/./-}d${DEBIAN_RELEASE/./-}-sv
# export GFS_CLIENT_NAME=gfs-${GFS_VERSION_MAJOR/./-}d${DEBIAN_RELEASE/./-}-cl
# export GFS_STORAGE=gfs-stor-${GFS_VERSION_MAJOR/./-}
# export GFS_SERVICE=gfs-${GFS_VERSION_MAJOR/./-}
export GFS_SERVER_NAME=gfs-server
export GFS_CLIENT_NAME=gfs-client
export GFS_STORAGE=gfs-stor
export GFS_SERVICE=gfs

export GFS_SERVER_IMAGE=${DOCKER_UID}/gfs:${DEBIAN_RELEASE}-${GFS_VERSION}
export GFS_CLIENT_IMAGE=${DOCKER_UID}/gfs-c:${DEBIAN_RELEASE}-${GFS_VERSION}

# root/usr/local/bin/run-init.sh
export GLUSTER_MOUNTPOINT=${GLUSTER_BRICK_PATH}/${GLUSTER_VOL}
export GLUSTER_VOLUME_SERVER=${GFS_SERVICE}.${NAMESPACE}.svc.cluster.local
export GLUSTER_VOLUME_ID=${GLUSTER_VOL}
