kind: List
apiVersion: v1
items:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: glusterfs
- kind: Service
  apiVersion: v1
  metadata:
    name: glusterfs-storage
  spec:
    ports:
    - name: ssh
      port: 2222
      targetPort: 2222
    - name: glusterfs-api
      port: 24007
      targetPort: 24007
    - name: glusterfs-infiniband
      port: 24008
      targetPort: 24008
    - name: glusterfs-brick0
      port: 49152
      targetPort: 49152
    - name: glusterfs-nfs-0
      port: 38465
      targetPort: 38465
    - name: glusterfs-nfs-1
      port: 38466
      targetPort: 38466
    - name: glusterfs-nfs-2
      port: 38467
      targetPort: 38467
    - name: nfs-rpc
      port: 111
      targetPort: 111
    - name: nfs-rpc-udp
      port: 111
      targetPort: 111
      protocol: UDP
    - name: nfs-portmap
      port: 2049
      targetPort: 2049
    selector:
      component: glusterfs-storage
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      component: glusterfs-storage
    name: glusterfs-storage
  spec:
    replicas: 2
    selector:
      component: glusterfs-storage
    template:
      metadata:
        labels:
          component: glusterfs-storage
      spec:
        serviceAccount: glusterfs
        containers:
        - name: glusterfs-server
          image: matthewvalimaki/glusterfs-kubernetes-server-debian8.3-3.5.2:latest
          securityContext:
            privileged: true
          ports:
          - containerPort: 2222
          - containerPort: 24007
          - containerPort: 24008
          - containerPort: 49152
          - containerPort: 38465
          - containerPort: 38466
          - containerPort: 38467
          - containerPort: 2049
          - containerPort: 111
          - containerPort: 111
            protocol: UDP
          env:
          - name: GLUSTER_BRICK_PATH
            value:
          - name: GLUSTER_VOL
            value: shared0
          - name: GLUSTER_BRICK_PATH
            value: /gluster_volume
          - name: SERVICE_NAME
            value: glusterfs-storage.default.svc.cluster.local
          - name: ROOT_PASSWORD
            value: container_root_password
          - name: DEBUG
            value: "1"
          - name: SSH_PORT
            value: "2222"
          volumeMounts:
            - name: local0
              mountPath: /gluster_volume
        volumes:
          - name: local0
            emptyDir: {}

      
      