#!/bin/bash
if [[ "$(which applytmpl)" == "" ]]; then
    if ! go get --tags netgo -ldflags '-w -s' github.com/davidwalter0/applytmpl; then
        echo applytmpl build failed
        exit 1
    fi
fi
. ../environment
set -x
if ! applytmpl < Dockerfile.tmpl > Dockerfile ; then
    echo Error processing template
    exit 1
fi
docker build --no-cache --tag=${DOCKER_UID}/glusterfs-server:debian${DEBIAN_RELEASE}-${GFS_VERSION} .
docker push ${DOCKER_UID}/glusterfs-server:debian${DEBIAN_RELEASE}-${GFS_VERSION}
set +x
