apiVersion: v1
kind: ReplicationController
metadata:
  name: gfs-c-d78-327
spec:
  replicas: 1
  selector:
    app: gfs-c-d78-327
  template:
    metadata:
      labels:
        app: gfs-c-d78-327
    spec:
      containers:
      - image: matthewvalimaki/glusterfs-kubernetes-client-debian7.8-3.2.7
        name: gfs-c-d78-327
        securityContext:
          privileged: true
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
